"""Customer payment simulation run from GitHub Actions runner (overseas network).
Airdrops devnet SOL to a fresh customer wallet and pays the shop's Solana Pay URL.
Retries airdrop for up to ~4.5h (official faucet occasionally has transient failures).
"""
import json, os, sys, time, base64, urllib.request

RPC_OFFICIAL = "https://api.devnet.solana.com"
RPC_LIST = [RPC_OFFICIAL, "https://api.testnet.solana.com", "https://devnet.rpcpool.com"]
REF = "D3YK5p4uJZQGwXtQv1K9HxNBe2AEVPbo7cQ8qWrS4mTn"
RECEIVER = "C7YH8TC2MgdQzFFG51RYVhYNCa8jfM6tCcErYaGkTcsB"

def rpc(rpc_url, method, params, timeout=40):
    body = json.dumps({"jsonrpc":"2.0","id":1,"method":method,"params":params}).encode()
    req = urllib.request.Request(rpc_url, data=body, headers={"Content-Type":"application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode())

def rpc_any(method, params, timeout=40):
    last = None
    for u in RPC_LIST:
        try:
            return u, rpc(u, method, params, timeout)
        except Exception as e:
            last = e
            continue
    raise last

from solders.keypair import Keypair
from solders.pubkey import Pubkey
from solders.hash import Hash
from solders.system_program import transfer, TransferParams
from solders.instruction import Instruction, AccountMeta
from solders.message import Message
from solders.transaction import Transaction

payer = Keypair()  # fresh address every run
print("customer:", payer.pubkey())

# check if already paid (previous run may have succeeded)
try:
    u, chk = rpc_any("getSignaturesForAddress", [REF, {"limit": 5}])
    if chk.get("result"):
        print("ALREADY_PAID:", json.dumps(chk["result"][0])[:200])
        sys.exit(0)
except Exception:
    pass

# long retry loop for airdrop (~4.5h max)
deadline = time.time() + 4.5 * 3600
got = False
attempt = 0
while time.time() < deadline and not got:
    attempt += 1
    for u in RPC_LIST:
        try:
            a = rpc(u, "requestAirdrop", [str(payer.pubkey()), 1000000000], timeout=25)
            if "result" in a:
                print(f"[{attempt}] airdrop OK via {u}: {a['result'][:40]}")
                got = True
                break
            else:
                print(f"[{attempt}] {u}: {str(a.get('error'))[:60]}")
        except Exception as e:
            print(f"[{attempt}] {u}: {str(e)[:50]}")
        time.sleep(2)
    if not got:
        time.sleep(28)

if not got:
    print("AIRDROP_NEVER_SUCCEEDED")
    sys.exit(1)

time.sleep(10)
_, bal = rpc_any("getBalance", [str(payer.pubkey())])
print("balance:", bal.get("result", {}).get("value", 0))
if bal.get("result", {}).get("value", 0) < 0.1e9:
    print("BALANCE_TOO_LOW")
    sys.exit(1)

# pay the Solana Pay URL generated by the ZeroClaw agent
url = f"solana:{RECEIVER}?amount=0.05&reference={REF}&label=Hermes%20Shop&message=Invoice%20%23101"
body = url.split(":", 1)[1]
addr_part, query_part = body.split("?", 1)
receiver = Pubkey.from_string(addr_part)
qs = dict(kv.split("=", 1) for kv in query_part.split("&"))
ref = Pubkey.from_string(qs["reference"])
amount = float(qs["amount"])
print("paying", amount, "SOL to", receiver, "ref", ref)

rpc_url, bh_resp = rpc_any("getLatestBlockhash", [])
bh = Hash.from_string(bh_resp["result"]["value"]["blockhash"])
ix1 = transfer(TransferParams(from_pubkey=payer.pubkey(), to_pubkey=receiver, lamports=int(amount*1e9)))
memo_prog = Pubkey.from_string("MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr")
ix2 = Instruction(program_id=memo_prog, data=b"solana-pay-reference", accounts=[AccountMeta(ref, False, False)])
msg = Message.new_with_blockhash([ix1, ix2], payer.pubkey(), bh)
tx = Transaction.new_unsigned(msg)
tx.sign([payer], bh)
sig = rpc(rpc_url, "sendTransaction", [base64.b64encode(bytes(tx)).decode(), {"encoding":"base64", "preflightCommitment":"confirmed"}])
print("TX:", json.dumps(sig.get("result", sig.get("error"))))

time.sleep(12)
chk = rpc(rpc_url, "getSignaturesForAddress", [qs["reference"], {"limit": 5}])
print("REF_SIGS:", json.dumps(chk.get("result"), indent=1)[:600])
