"""Customer payment simulation run from GitHub Actions runner (overseas network).
Airdrops devnet SOL to the customer wallet and pays the shop's Solana Pay URL.
"""
import json, os, sys, time, urllib.request

RPC = "https://api.devnet.solana.com"

def rpc(method, params, timeout=40):
    body = json.dumps({"jsonrpc":"2.0","id":1,"method":method,"params":params}).encode()
    req = urllib.request.Request(RPC, data=body, headers={"Content-Type":"application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode())

from solders.keypair import Keypair
from solders.pubkey import Pubkey
from solders.system_program import transfer, TransferParams
from solders.instruction import Instruction, AccountMeta
from solders.message import Message
from solders.transaction import Transaction

payer = Keypair.from_bytes(bytes.fromhex(os.environ["PAYER_KEY"]))
print("customer:", payer.pubkey())

bal = rpc("getBalance", [str(payer.pubkey())])
if bal.get("result", {}).get("value", 0) < 0.1e9:
    for i in range(8):
        try:
            a = rpc("requestAirdrop", [str(payer.pubkey()), 2000000000])
            if "result" in a:
                print("airdrop ok:", a["result"][:40])
                break
        except Exception as e:
            print(f"airdrop try {i}: {str(e)[:60]}")
        time.sleep(10)

# The Solana Pay URL generated by the ZeroClaw agent (from the demo):
url = "solana:C7YH8TC2MgdQzFFG51RYVhYNCa8jfM6tCcErYaGkTcsB?amount=0.05&reference=D3YK5p4uJZQGwXtQv1K9HxNBe2AEVPbo7cQ8qWrS4mTn&label=Hermes%20Shop&message=Invoice%20%23101"
body = url.split(":", 1)[1]
addr_part, query_part = body.split("?", 1)
receiver = Pubkey.from_string(addr_part)
qs = dict(kv.split("=", 1) for kv in query_part.split("&"))
ref = Pubkey.from_string(qs["reference"])
amount = float(qs["amount"])
print("paying", amount, "SOL to", receiver, "ref", ref)

bh = rpc("getLatestBlockhash", [])["result"]["value"]["blockhash"]
ix1 = transfer(TransferParams(from_pubkey=payer.pubkey(), to_pubkey=receiver, lamports=int(amount*1e9)))
memo_prog = Pubkey.from_string("MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr")
ix2 = Instruction(program_id=memo_prog, data=b"solana-pay-reference", accounts=[AccountMeta(ref, False, False)])
msg = Message.new_with_blockhash([ix1, ix2], payer.pubkey(), Pubkey.from_string(bh))
tx = Transaction.new_unsigned(msg)
tx.sign([payer], Pubkey.from_string(bh))
sig = rpc("sendTransaction", [bytes(tx).hex(), {"encoding":"base64", "preflightCommitment":"confirmed"}])
print("TX:", json.dumps(sig.get("result", sig.get("error"))))

# verify reference key now has signatures
time.sleep(8)
chk = rpc("getSignaturesForAddress", [qs["reference"], {"limit": 5}])
print("REF_SIGS:", json.dumps(chk.get("result"), indent=1)[:500])
