"""Customer payment simulation run from GitHub Actions runner (overseas network).
Airdrops devnet SOL to the customer wallet and pays the shop's Solana Pay URL.
Idempotent: if already paid, just verifies and exits 0.
"""
import json, os, sys, time, base64, urllib.request

RPC_LIST = [
    "https://api.testnet.solana.com",
    "https://api.devnet.solana.com",
    "https://devnet.rpcpool.com",
]
REF = "D3YK5p4uJZQGwXtQv1K9HxNBe2AEVPbo7cQ8qWrS4mTn"

def rpc(rpc_url, method, params, timeout=40):
    body = json.dumps({"jsonrpc":"2.0","id":1,"method":method,"params":params}).encode()
    req = urllib.request.Request(rpc_url, data=body, headers={"Content-Type":"application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode())

def rpc_any(method, params, timeout=40):
    last = None
    for u in RPC_LIST:
        try:
            return u, rpc(u, method, params, timeout)
        except Exception as e:
            last = e
            continue
    raise last

from solders.keypair import Keypair
from solders.pubkey import Pubkey
from solders.hash import Hash
from solders.system_program import transfer, TransferParams
from solders.instruction import Instruction, AccountMeta
from solders.message import Message
from solders.transaction import Transaction

payer = Keypair.from_bytes(bytes.fromhex(os.environ["PAYER_KEY"]))
print("customer:", payer.pubkey())

# already paid?
try:
    u, chk = rpc_any("getSignaturesForAddress", [REF, {"limit": 5}])
    if chk.get("result"):
        print("ALREADY_PAID - verification:", json.dumps(chk["result"][0])[:200])
        sys.exit(0)
except Exception as e:
    print("check err:", str(e)[:60])

# ensure balance
_, bal = rpc_any("getBalance", [str(payer.pubkey())])
have = bal.get("result", {}).get("value", 0)
print("balance:", have)
if have < 0.1e9:
    done = False
    for i in range(6):
        for u in RPC_LIST:
            try:
                a = rpc(u, "requestAirdrop", [str(payer.pubkey()), 2000000000], timeout=25)
                if "result" in a:
                    print(f"airdrop ok via {u}:", a["result"][:40])
                    done = True
                    break
            except Exception:
                pass
        if done:
            break
        time.sleep(15)
    time.sleep(8)
    _, bal2 = rpc_any("getBalance", [str(payer.pubkey())])
    have = bal2.get("result", {}).get("value", 0)
    print("balance after airdrop:", have)
    if have < 0.1e9:
        print("AIRDROP_STILL_FAILING - will retry next scheduled run")
        sys.exit(1)  # fail so we can see it in run list; scheduler retries

# The Solana Pay URL generated by the ZeroClaw agent (from the demo):
url = "solana:C7YH8TC2MgdQzFFG51RYVhYNCa8jfM6tCcErYaGkTcsB?amount=0.05&reference=D3YK5p4uJZQGwXtQv1K9HxNBe2AEVPbo7cQ8qWrS4mTn&label=Hermes%20Shop&message=Invoice%20%23101"
body = url.split(":", 1)[1]
addr_part, query_part = body.split("?", 1)
receiver = Pubkey.from_string(addr_part)
qs = dict(kv.split("=", 1) for kv in query_part.split("&"))
ref = Pubkey.from_string(qs["reference"])
amount = float(qs["amount"])
print("paying", amount, "SOL to", receiver, "ref", ref)

rpc_url, bh_resp = rpc_any("getLatestBlockhash", [])
bh = Hash.from_string(bh_resp["result"]["value"]["blockhash"])
ix1 = transfer(TransferParams(from_pubkey=payer.pubkey(), to_pubkey=receiver, lamports=int(amount*1e9)))
memo_prog = Pubkey.from_string("MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr")
ix2 = Instruction(program_id=memo_prog, data=b"solana-pay-reference", accounts=[AccountMeta(ref, False, False)])
msg = Message.new_with_blockhash([ix1, ix2], payer.pubkey(), bh)
tx = Transaction.new_unsigned(msg)
tx.sign([payer], bh)
sig = rpc(rpc_url, "sendTransaction", [base64.b64encode(bytes(tx)).decode(), {"encoding":"base64", "preflightCommitment":"confirmed"}])
print("TX via", rpc_url, ":", json.dumps(sig.get("result", sig.get("error"))))

time.sleep(10)
chk = rpc(rpc_url, "getSignaturesForAddress", [qs["reference"], {"limit": 5}])
print("REF_SIGS:", json.dumps(chk.get("result"), indent=1)[:600])
